export const metricDefinitions = [
  // ECONOMIC_CORE
  {
    code: 'GDP_NOMINAL',
    name: 'GDP (Nominal USD)',
    category: 'ECONOMIC_CORE',
    unit: 'billion USD',
    isQuarterly: true,
    searchHints: ['GDP', 'gross domestic product', 'economy size'],
  },
  {
    code: 'GDP_PPP',
    name: 'GDP (PPP)',
    category: 'ECONOMIC_CORE',
    unit: 'billion USD',
    isQuarterly: false,
    searchHints: ['GDP PPP', 'purchasing power parity'],
  },
  {
    code: 'GDP_GROWTH',
    name: 'GDP Growth Rate',
    category: 'ECONOMIC_CORE',
    unit: '%',
    isQuarterly: true,
    minValue: -50,
    maxValue: 50,
    searchHints: ['GDP growth', 'economic growth rate'],
  },
  {
    code: 'GDP_PER_CAPITA',
    name: 'GDP Per Capita',
    category: 'ECONOMIC_CORE',
    unit: 'USD',
    isQuarterly: false,
    searchHints: ['GDP per capita', 'income per person'],
  },
  {
    code: 'GOVT_DEBT_ABSOLUTE',
    name: 'Government Debt',
    category: 'ECONOMIC_CORE',
    unit: 'billion USD',
    isQuarterly: false,
    searchHints: ['government debt', 'national debt', 'public debt'],
  },
  {
    code: 'GOVT_DEBT_GDP_RATIO',
    name: 'Debt to GDP Ratio',
    category: 'ECONOMIC_CORE',
    unit: '%',
    minValue: 0,
    maxValue: 500,
    isQuarterly: false,
    searchHints: ['debt to GDP', 'debt ratio'],
  },
  {
    code: 'INFLATION_RATE',
    name: 'Inflation Rate (CPI)',
    category: 'ECONOMIC_CORE',
    unit: '%',
    isQuarterly: true,
    minValue: -20,
    maxValue: 1000,
    searchHints: ['inflation', 'CPI', 'consumer price index'],
  },
  {
    code: 'INTEREST_RATE',
    name: 'Central Bank Interest Rate',
    category: 'ECONOMIC_CORE',
    unit: '%',
    isQuarterly: true,
    minValue: -5,
    maxValue: 100,
    searchHints: ['interest rate', 'central bank rate', 'policy rate'],
  },
  {
    code: 'EXCHANGE_RATE_USD',
    name: 'Exchange Rate (vs USD)',
    category: 'ECONOMIC_CORE',
    unit: 'local/USD',
    isQuarterly: true,
    searchHints: ['exchange rate', 'currency', 'USD'],
  },
  {
    code: 'TRADE_BALANCE',
    name: 'Trade Balance',
    category: 'ECONOMIC_CORE',
    unit: 'billion USD',
    isQuarterly: true,
    searchHints: ['trade balance', 'exports imports', 'trade deficit surplus'],
  },
  {
    code: 'CURRENT_ACCOUNT',
    name: 'Current Account Balance',
    category: 'ECONOMIC_CORE',
    unit: 'billion USD',
    isQuarterly: true,
    searchHints: ['current account', 'balance of payments'],
  },
  {
    code: 'FOREIGN_RESERVES',
    name: 'Foreign Exchange Reserves',
    category: 'ECONOMIC_CORE',
    unit: 'billion USD',
    isQuarterly: true,
    searchHints: ['foreign reserves', 'forex reserves', 'international reserves'],
  },
  {
    code: 'FDI_NET',
    name: 'Foreign Direct Investment (Net)',
    category: 'ECONOMIC_CORE',
    unit: 'billion USD',
    isQuarterly: true,
    searchHints: ['FDI', 'foreign direct investment', 'foreign investment'],
  },
  {
    code: 'BUDGET_BALANCE',
    name: 'Budget Deficit/Surplus',
    category: 'ECONOMIC_CORE',
    unit: '% of GDP',
    isQuarterly: false,
    searchHints: ['budget deficit', 'budget surplus', 'fiscal balance'],
  },

  // ECONOMIC_MARKET
  {
    code: 'STOCK_INDEX_LEVEL',
    name: 'Stock Market Index',
    category: 'ECONOMIC_MARKET',
    unit: 'points',
    isQuarterly: true,
    searchHints: ['stock market', 'stock index', 'equity market'],
  },
  {
    code: 'STOCK_INDEX_RETURN',
    name: 'Stock Market Quarterly Return',
    category: 'ECONOMIC_MARKET',
    unit: '%',
    isQuarterly: true,
    searchHints: ['stock market return', 'equity return'],
  },
  {
    code: 'BOND_YIELD_10Y',
    name: '10-Year Bond Yield',
    category: 'ECONOMIC_MARKET',
    unit: '%',
    isQuarterly: true,
    searchHints: ['bond yield', '10 year bond', 'government bond'],
  },
  {
    code: 'CREDIT_RATING',
    name: 'Sovereign Credit Rating',
    category: 'ECONOMIC_MARKET',
    dataType: 'string',
    isQuarterly: false,
    searchHints: ['credit rating', 'S&P rating', "Moody's", 'Fitch'],
  },
  {
    code: 'BUSINESS_CONFIDENCE',
    name: 'Business Confidence Index',
    category: 'ECONOMIC_MARKET',
    unit: 'index',
    isQuarterly: true,
    searchHints: ['business confidence', 'business sentiment'],
  },
  {
    code: 'CONSUMER_CONFIDENCE',
    name: 'Consumer Confidence Index',
    category: 'ECONOMIC_MARKET',
    unit: 'index',
    isQuarterly: true,
    searchHints: ['consumer confidence', 'consumer sentiment'],
  },
  {
    code: 'PMI',
    name: 'Purchasing Managers Index',
    category: 'ECONOMIC_MARKET',
    unit: 'index',
    minValue: 0,
    maxValue: 100,
    isQuarterly: true,
    searchHints: ['PMI', 'purchasing managers index', 'manufacturing PMI'],
  },

  // LABOR_INCOME
  {
    code: 'UNEMPLOYMENT_RATE',
    name: 'Unemployment Rate',
    category: 'LABOR_INCOME',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    isQuarterly: true,
    searchHints: ['unemployment', 'jobless rate'],
  },
  {
    code: 'UNEMPLOYMENT_DIRECTION',
    name: 'Unemployment Direction',
    category: 'LABOR_INCOME',
    dataType: 'string',
    isQuarterly: true,
    searchHints: ['unemployment trend', 'jobs trend'],
  },
  {
    code: 'LABOR_PARTICIPATION',
    name: 'Labor Force Participation Rate',
    category: 'LABOR_INCOME',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    isQuarterly: false,
    searchHints: ['labor participation', 'workforce participation'],
  },
  {
    code: 'YOUTH_UNEMPLOYMENT',
    name: 'Youth Unemployment (15-24)',
    category: 'LABOR_INCOME',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    isQuarterly: false,
    searchHints: ['youth unemployment', 'young people unemployment'],
  },
  {
    code: 'MEDIAN_INCOME',
    name: 'Median Household Income',
    category: 'LABOR_INCOME',
    unit: 'USD',
    isQuarterly: false,
    searchHints: ['median income', 'household income', 'median wage'],
  },
  {
    code: 'AVERAGE_WAGE',
    name: 'Average Wage',
    category: 'LABOR_INCOME',
    unit: 'USD/month',
    isQuarterly: false,
    searchHints: ['average wage', 'average salary', 'mean wage'],
  },
  {
    code: 'WAGE_GROWTH',
    name: 'Wage Growth',
    category: 'LABOR_INCOME',
    unit: '%',
    isQuarterly: true,
    searchHints: ['wage growth', 'salary increase', 'pay rise'],
  },
  {
    code: 'MINIMUM_WAGE',
    name: 'Minimum Wage',
    category: 'LABOR_INCOME',
    unit: 'USD/month',
    isQuarterly: false,
    searchHints: ['minimum wage', 'minimum salary'],
  },
  {
    code: 'GINI_COEFFICIENT',
    name: 'Gini Coefficient',
    category: 'LABOR_INCOME',
    unit: 'index',
    minValue: 0,
    maxValue: 1,
    isQuarterly: false,
    searchHints: ['gini', 'inequality', 'income inequality'],
  },
  {
    code: 'POVERTY_RATE_NATIONAL',
    name: 'Poverty Rate (National)',
    category: 'LABOR_INCOME',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    isQuarterly: false,
    searchHints: ['poverty rate', 'poverty level'],
  },

  // COST_OF_LIVING
  {
    code: 'CPI_INDEX',
    name: 'Consumer Price Index',
    category: 'COST_OF_LIVING',
    unit: 'index',
    isQuarterly: true,
    searchHints: ['CPI', 'consumer price index'],
  },
  {
    code: 'HOUSING_PRICE_INDEX',
    name: 'Housing Price Index',
    category: 'COST_OF_LIVING',
    unit: 'index',
    isQuarterly: true,
    searchHints: ['housing prices', 'property prices', 'real estate prices'],
  },
  {
    code: 'RENT_INDEX',
    name: 'Rent Index (Major City)',
    category: 'COST_OF_LIVING',
    unit: 'index',
    isQuarterly: true,
    searchHints: ['rent prices', 'rental costs'],
  },
  {
    code: 'FOOD_PRICE_INDEX',
    name: 'Food Price Index',
    category: 'COST_OF_LIVING',
    unit: 'index',
    isQuarterly: true,
    searchHints: ['food prices', 'food inflation'],
  },
  {
    code: 'ENERGY_PRICE_INDEX',
    name: 'Energy Price Index',
    category: 'COST_OF_LIVING',
    unit: 'index',
    isQuarterly: true,
    searchHints: ['energy prices', 'electricity prices', 'fuel prices'],
  },

  // INDUSTRY
  {
    code: 'INDUSTRY_1_NAME',
    name: 'Top Industry #1 (by GDP)',
    category: 'INDUSTRY',
    dataType: 'string',
    isQuarterly: false,
    searchHints: ['largest industry', 'main industry', 'top sector'],
  },
  {
    code: 'INDUSTRY_1_GDP_SHARE',
    name: 'Top Industry #1 GDP Share',
    category: 'INDUSTRY',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    isQuarterly: false,
    searchHints: ['industry GDP share', 'sector contribution'],
  },
  {
    code: 'INDUSTRY_1_DIRECTION',
    name: 'Top Industry #1 Direction',
    category: 'INDUSTRY',
    dataType: 'string',
    isQuarterly: true,
    searchHints: ['industry growth', 'sector trend'],
  },
  {
    code: 'INDUSTRY_2_NAME',
    name: 'Top Industry #2 (by GDP)',
    category: 'INDUSTRY',
    dataType: 'string',
    isQuarterly: false,
    searchHints: ['second largest industry'],
  },
  {
    code: 'INDUSTRY_2_GDP_SHARE',
    name: 'Top Industry #2 GDP Share',
    category: 'INDUSTRY',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    isQuarterly: false,
    searchHints: [],
  },
  {
    code: 'INDUSTRY_2_DIRECTION',
    name: 'Top Industry #2 Direction',
    category: 'INDUSTRY',
    dataType: 'string',
    isQuarterly: true,
    searchHints: [],
  },
  {
    code: 'INDUSTRY_3_NAME',
    name: 'Top Industry #3 (by GDP)',
    category: 'INDUSTRY',
    dataType: 'string',
    isQuarterly: false,
    searchHints: [],
  },
  {
    code: 'INDUSTRY_3_GDP_SHARE',
    name: 'Top Industry #3 GDP Share',
    category: 'INDUSTRY',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    isQuarterly: false,
    searchHints: [],
  },
  {
    code: 'INDUSTRY_3_DIRECTION',
    name: 'Top Industry #3 Direction',
    category: 'INDUSTRY',
    dataType: 'string',
    isQuarterly: true,
    searchHints: [],
  },
  {
    code: 'MANUFACTURING_OUTPUT',
    name: 'Manufacturing Output Index',
    category: 'INDUSTRY',
    unit: 'index',
    isQuarterly: true,
    searchHints: ['manufacturing output', 'industrial production'],
  },
  {
    code: 'SERVICES_GDP_SHARE',
    name: 'Services Sector (% of GDP)',
    category: 'INDUSTRY',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    isQuarterly: false,
    searchHints: ['services sector', 'tertiary sector'],
  },
  {
    code: 'AGRICULTURE_GDP_SHARE',
    name: 'Agriculture (% of GDP)',
    category: 'INDUSTRY',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    isQuarterly: false,
    searchHints: ['agriculture GDP', 'farming sector'],
  },
  {
    code: 'EXPORT_GROWTH',
    name: 'Export Growth',
    category: 'INDUSTRY',
    unit: '%',
    isQuarterly: true,
    searchHints: ['export growth', 'exports increase'],
  },
  {
    code: 'IMPORT_GROWTH',
    name: 'Import Growth',
    category: 'INDUSTRY',
    unit: '%',
    isQuarterly: true,
    searchHints: ['import growth', 'imports increase'],
  },

  // DEMOGRAPHICS
  {
    code: 'POPULATION',
    name: 'Population',
    category: 'DEMOGRAPHICS',
    unit: 'millions',
    isQuarterly: false,
    searchHints: ['population', 'inhabitants'],
  },
  {
    code: 'POPULATION_GROWTH',
    name: 'Population Growth Rate',
    category: 'DEMOGRAPHICS',
    unit: '%',
    isQuarterly: false,
    searchHints: ['population growth', 'demographic growth'],
  },
  {
    code: 'BIRTH_RATE',
    name: 'Birth Rate',
    category: 'DEMOGRAPHICS',
    unit: 'per 1,000',
    isQuarterly: false,
    searchHints: ['birth rate', 'fertility', 'births'],
  },
  {
    code: 'DEATH_RATE',
    name: 'Death Rate',
    category: 'DEMOGRAPHICS',
    unit: 'per 1,000',
    isQuarterly: false,
    searchHints: ['death rate', 'mortality rate'],
  },
  {
    code: 'INFANT_MORTALITY',
    name: 'Infant Mortality Rate',
    category: 'DEMOGRAPHICS',
    unit: 'per 1,000 live births',
    isQuarterly: false,
    searchHints: ['infant mortality', 'child mortality'],
  },
  {
    code: 'LIFE_EXPECTANCY',
    name: 'Life Expectancy',
    category: 'DEMOGRAPHICS',
    unit: 'years',
    minValue: 30,
    maxValue: 100,
    isQuarterly: false,
    searchHints: ['life expectancy', 'lifespan'],
  },
  {
    code: 'MEDIAN_AGE',
    name: 'Median Age',
    category: 'DEMOGRAPHICS',
    unit: 'years',
    minValue: 10,
    maxValue: 60,
    isQuarterly: false,
    searchHints: ['median age', 'average age', 'population age'],
  },
  {
    code: 'URBANIZATION_RATE',
    name: 'Urbanization Rate',
    category: 'DEMOGRAPHICS',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    isQuarterly: false,
    searchHints: ['urbanization', 'urban population'],
  },
  {
    code: 'NET_MIGRATION',
    name: 'Net Migration Rate',
    category: 'DEMOGRAPHICS',
    unit: 'per 1,000',
    isQuarterly: false,
    searchHints: ['net migration', 'immigration emigration'],
  },
  {
    code: 'IMMIGRATION_ABSOLUTE',
    name: 'Immigration (Absolute)',
    category: 'DEMOGRAPHICS',
    unit: 'thousands',
    isQuarterly: false,
    searchHints: ['immigration numbers', 'immigrants'],
  },
  {
    code: 'EMIGRATION_ABSOLUTE',
    name: 'Emigration (Absolute)',
    category: 'DEMOGRAPHICS',
    unit: 'thousands',
    isQuarterly: false,
    searchHints: ['emigration numbers', 'emigrants'],
  },
  {
    code: 'REFUGEE_POPULATION',
    name: 'Refugee Population Hosted',
    category: 'DEMOGRAPHICS',
    unit: 'thousands',
    isQuarterly: false,
    searchHints: ['refugees', 'asylum seekers'],
  },

  // HEALTH_WELLBEING
  {
    code: 'SUICIDE_RATE',
    name: 'Suicide Rate',
    category: 'HEALTH_WELLBEING',
    unit: 'per 100,000',
    isQuarterly: false,
    searchHints: ['suicide rate', 'self-harm rate'],
  },
  {
    code: 'HOMICIDE_RATE',
    name: 'Homicide Rate',
    category: 'HEALTH_WELLBEING',
    unit: 'per 100,000',
    isQuarterly: false,
    searchHints: ['homicide rate', 'murder rate'],
  },
  {
    code: 'CRIME_INDEX',
    name: 'Crime Index',
    category: 'HEALTH_WELLBEING',
    unit: 'index',
    isQuarterly: false,
    searchHints: ['crime rate', 'crime index', 'safety'],
  },
  {
    code: 'HEALTHCARE_SPENDING_GDP',
    name: 'Healthcare Spending (% GDP)',
    category: 'HEALTH_WELLBEING',
    unit: '%',
    minValue: 0,
    maxValue: 30,
    isQuarterly: false,
    searchHints: ['healthcare spending', 'health expenditure'],
  },
  {
    code: 'HOSPITAL_BEDS',
    name: 'Hospital Beds',
    category: 'HEALTH_WELLBEING',
    unit: 'per 1,000',
    isQuarterly: false,
    searchHints: ['hospital beds', 'healthcare capacity'],
  },
  {
    code: 'PHYSICIANS',
    name: 'Physicians',
    category: 'HEALTH_WELLBEING',
    unit: 'per 1,000',
    isQuarterly: false,
    searchHints: ['doctors', 'physicians per capita'],
  },

  // EDUCATION
  {
    code: 'LITERACY_RATE',
    name: 'Literacy Rate',
    category: 'EDUCATION',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    isQuarterly: false,
    searchHints: ['literacy rate', 'reading writing'],
  },
  {
    code: 'EDUCATION_SPENDING_GDP',
    name: 'Education Spending (% GDP)',
    category: 'EDUCATION',
    unit: '%',
    minValue: 0,
    maxValue: 20,
    isQuarterly: false,
    searchHints: ['education spending', 'education expenditure'],
  },
  {
    code: 'TERTIARY_ENROLLMENT',
    name: 'Tertiary Enrollment Rate',
    category: 'EDUCATION',
    unit: '%',
    minValue: 0,
    maxValue: 150,
    isQuarterly: false,
    searchHints: ['university enrollment', 'higher education'],
  },

  // POLITICAL_STRUCTURE
  {
    code: 'RULING_PARTY',
    name: 'Ruling Party/Coalition',
    category: 'POLITICAL_STRUCTURE',
    dataType: 'string',
    isQuarterly: false,
    searchHints: ['ruling party', 'government party', 'governing coalition'],
  },
  {
    code: 'HEAD_OF_GOVERNMENT',
    name: 'Head of Government',
    category: 'POLITICAL_STRUCTURE',
    dataType: 'string',
    isQuarterly: false,
    searchHints: ['prime minister', 'president', 'head of government'],
  },
  {
    code: 'GOVT_SEAT_SHARE',
    name: 'Government Parliamentary Seat Share',
    category: 'POLITICAL_STRUCTURE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    isQuarterly: false,
    searchHints: ['parliament seats', 'majority', 'coalition seats'],
  },
  {
    code: 'YEARS_SINCE_ELECTION',
    name: 'Years Since Last Election',
    category: 'POLITICAL_STRUCTURE',
    unit: 'years',
    isQuarterly: false,
    searchHints: ['last election', 'previous election'],
  },
  {
    code: 'MONTHS_UNTIL_ELECTION',
    name: 'Months Until Next Election',
    category: 'POLITICAL_STRUCTURE',
    unit: 'months',
    isQuarterly: true,
    searchHints: ['next election', 'upcoming election'],
  },

  // POLITICAL_SENTIMENT
  {
    code: 'GOVT_APPROVAL',
    name: 'Government Approval Rating',
    category: 'POLITICAL_SENTIMENT',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    isQuarterly: true,
    searchHints: ['government approval', 'approval rating', 'popularity poll'],
  },
  {
    code: 'OPPOSITION_POLLING',
    name: 'Main Opposition Polling',
    category: 'POLITICAL_SENTIMENT',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    isQuarterly: true,
    searchHints: ['opposition polling', 'opposition party poll'],
  },
  {
    code: 'POLITICAL_STABILITY_INDEX',
    name: 'Political Stability Index',
    category: 'POLITICAL_SENTIMENT',
    unit: 'index',
    isQuarterly: false,
    searchHints: ['political stability', 'governance stability'],
  },
  {
    code: 'CORRUPTION_INDEX',
    name: 'Corruption Perceptions Index',
    category: 'POLITICAL_SENTIMENT',
    unit: 'index (0-100)',
    minValue: 0,
    maxValue: 100,
    isQuarterly: false,
    searchHints: ['corruption index', 'transparency international'],
  },
  {
    code: 'DEMOCRACY_INDEX',
    name: 'Democracy Index',
    category: 'POLITICAL_SENTIMENT',
    unit: 'index (0-10)',
    minValue: 0,
    maxValue: 10,
    isQuarterly: false,
    searchHints: ['democracy index', 'economist democracy'],
  },
  {
    code: 'PRESS_FREEDOM_INDEX',
    name: 'Press Freedom Index',
    category: 'POLITICAL_SENTIMENT',
    unit: 'index',
    isQuarterly: false,
    searchHints: ['press freedom', 'media freedom'],
  },

  // SOCIAL_SENTIMENT
  {
    code: 'ECONOMIC_OUTLOOK_SENTIMENT',
    name: 'Economic Outlook Sentiment',
    category: 'SOCIAL_SENTIMENT',
    dataType: 'string',
    isQuarterly: true,
    searchHints: ['economic outlook', 'economic sentiment', 'economy direction'],
  },
  {
    code: 'IMMIGRATION_POLICY_SENTIMENT',
    name: 'Immigration Policy Sentiment',
    category: 'SOCIAL_SENTIMENT',
    dataType: 'string',
    isQuarterly: true,
    searchHints: ['immigration policy', 'immigration debate'],
  },
  {
    code: 'GOVT_TRUST_LEVEL',
    name: 'Government Trust Level',
    category: 'SOCIAL_SENTIMENT',
    dataType: 'string',
    isQuarterly: true,
    searchHints: ['trust in government', 'confidence in government'],
  },
  {
    code: 'SOCIAL_COHESION',
    name: 'Social Cohesion Assessment',
    category: 'SOCIAL_SENTIMENT',
    dataType: 'string',
    isQuarterly: true,
    searchHints: ['social cohesion', 'social unity', 'social division'],
  },
  {
    code: 'PROTEST_ACTIVITY_LEVEL',
    name: 'Protest Activity Level',
    category: 'SOCIAL_SENTIMENT',
    unit: 'scale 1-5',
    minValue: 1,
    maxValue: 5,
    isQuarterly: true,
    searchHints: ['protests', 'demonstrations', 'civil unrest'],
  },

  // SECURITY
  {
    code: 'MILITARY_SPENDING_GDP',
    name: 'Military Spending (% GDP)',
    category: 'SECURITY',
    unit: '%',
    minValue: 0,
    maxValue: 20,
    isQuarterly: false,
    searchHints: ['military spending', 'defense budget'],
  },
  {
    code: 'ACTIVE_CONFLICTS',
    name: 'Active Armed Conflicts',
    category: 'SECURITY',
    dataType: 'string',
    isQuarterly: true,
    searchHints: ['armed conflict', 'war', 'military conflict'],
  },
  {
    code: 'TERRORISM_INCIDENTS',
    name: 'Terrorism Incidents (Quarterly)',
    category: 'SECURITY',
    unit: 'count',
    isQuarterly: true,
    searchHints: ['terrorism', 'terrorist attacks'],
  },
  {
    code: 'CIVIL_UNREST_LEVEL',
    name: 'Civil Unrest Level',
    category: 'SECURITY',
    unit: 'scale 1-5',
    minValue: 1,
    maxValue: 5,
    isQuarterly: true,
    searchHints: ['civil unrest', 'riots', 'social unrest'],
  },

  // INFRASTRUCTURE
  {
    code: 'INTERNET_PENETRATION',
    name: 'Internet Penetration',
    category: 'INFRASTRUCTURE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    isQuarterly: false,
    searchHints: ['internet users', 'internet penetration'],
  },
  {
    code: 'MOBILE_SUBSCRIPTIONS',
    name: 'Mobile Subscriptions',
    category: 'INFRASTRUCTURE',
    unit: 'per 100 people',
    isQuarterly: false,
    searchHints: ['mobile subscriptions', 'cell phone users'],
  },
  {
    code: 'ELECTRICITY_ACCESS',
    name: 'Electricity Access',
    category: 'INFRASTRUCTURE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    isQuarterly: false,
    searchHints: ['electricity access', 'electrification'],
  },
  {
    code: 'RENEWABLE_ENERGY_SHARE',
    name: 'Renewable Energy Share',
    category: 'INFRASTRUCTURE',
    unit: '%',
    minValue: 0,
    maxValue: 100,
    isQuarterly: false,
    searchHints: ['renewable energy', 'clean energy', 'green energy'],
  },
];
